"""empty message

Revision ID: a1ae6402e63c
Revises: 
Create Date: 2017-03-11 15:28:34.230829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ae6402e63c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userimage', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('userfname', sa.String(length=256), nullable=True),
    sa.Column('userlname', sa.String(length=256), nullable=True),
    sa.Column('biography', sa.String(length=400), nullable=True),
    sa.Column('userage', sa.Integer(), nullable=True),
    sa.Column('usersex', sa.String(length=10), nullable=True),
    sa.Column('useraddon', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
